### ISSUE TITLE
Pop & parent behavior seems unintuitive

### ISSUE THREAD

**Issue by matklad** [udoprog/relative-path#11]
If I have a single-elemt path like `src`, it's parent is None and pop is a no-op. I'd expect the parent and the result after pop to be an empty path or `./` path.

**Comment by udoprog** [comment]
Marking it as bug for now.

I believe the reasoning behind this is that `Path::new("")` is rather nonsensical in `std`. It's always something that I've had to special case for, so I decided on this to avoid it. Also having `pop` transform a `RelativePathBuf` into a `"."` would require more work than a simple truncation. But the end result makes sense to me, so it's worth it.

#8 should also be fixed to make sure that `RelativePath::new(".") != RelativePath::new("")`.

**Comment by udoprog** [comment]
Another one which is a bit nonsensical and we've inherited from std:

What's the parent of `RelativePath::new("..").parent()`? It would also imo make sense to be `None`, but for `std::path::Path` it's `Some("")`:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1806a59d137fad6e46d06a6452bd10b0
