### ISSUE TITLE
Require `#[repr(C)]` for `RelativePath`

### ISSUE THREAD

**Issue by lo48576** [udoprog/relative-path#2]
I heard that the code such as below is unsound (lead to undefined behaviour):

https://github.com/udoprog/relative-path/blob/49d76f3aac512d1212c2a253f3f7264224edf88b/src/lib.rs#L271-L280

`RelativePath` type should have `#[repr(C)]` (stable) or `#[repr(transparent)]` ([unstable](https://github.com/rust-lang/rust/issues/43036)) to be safe.

This is because Rust doesn't guarantee that `str` and `RelativePath` have the same internal representations (and it will be guaranteed by `#[repr(C)]`).

For detail:

  * [OpaqueTypedefUnsized::from_* are unsound · Issue #1 · lo48576/opaque_typedef](https://github.com/lo48576/opaque_typedef/issues/1)
  * [UncasedStr::new is undefined behavior · Issue #494 · SergioBenitez/Rocket](https://github.com/SergioBenitez/Rocket/issues/494)

**Comment by udoprog** [comment]
Also: https://github.com/rust-lang/rust/issues/45910

Yeah, I'm keeping an eye on the stabilization for `#[repr(transparent)]` for this. I guess we could consider using `#[repr(C)]` until then.

**Comment by udoprog** [comment]
Fixed in 20d222a99a6f58e142170a6f630f13ced64734cd
