### ISSUE TITLE
Allow building a RelativePathBuf from a Path or Component iterable

### ISSUE THREAD

**Issue by not-my-profile** [udoprog/relative-path#24]
While this library does provide `RelativePath::normalize()`, you might want a different normalization method. For my current project I want to abort as soon as a  `ParentDir` component is discovered. With `std::path` this can be easily implemented as:

```rs
fn normalize_path(path: &Path) -> Result<PathBuf, &'static str> {
    let mut comps = Vec::new();
    for comp in path.components() {
        match comp {
            Component::Normal(_) => comps.push(comp),
            Component::ParentDir => return Err("no ../ component allowed"),
            _ => {}
        }
    }
    Ok(comps.iter().collect())
}
```

Which is made possible by two very handy implementations:

* `impl<P: AsRef<Path>> FromIterator<P> for PathBuf`
* `impl AsRef<Path> for Component<'_>`

It would be great if relative-path could offer the same implementations for its types, so:

* `impl<P: AsRef<RelativePath>> FromIterator<P> for RelativePathBuf`
* `impl AsRef<RelativePath> for relative_path::Component<'_>`

**Comment by udoprog** [comment]
I don't mind adding `FromIterator` impls since a goal of `relative-path` is to be as compatible as possible to `std::path`.

Do note that for this specific example collecting incurs an extra allocation which can be avoided by doing this with both `PathBuf` and `RelativePathBuf`:
```rust
fn normalize_path(path: &Path) -> Result<PathBuf, &'static str> {
    let mut buf = PathBuf::new();
    for comp in path.components() {
        match comp {
            Component::Normal(_) => buf.push(comp),
            Component::ParentDir => return Err("no ../ component allowed"),
            _ => {}
        }
    }
    Ok(buf)
}
```
