### ISSUE TITLE
.relative() yelds noting on paths, starting with ..

### ISSUE THREAD

**Issue by Gordon01** [udoprog/relative-path#30]
```
info!("Base {:?} name {:?}", dir, name);
let path = RelativePath::new(&dir).relative(RelativePath::from_path(&name).unwrap());
let name_str = path.as_str();
info!("File path {:?} Parent {:?}", path, path.parent());
```
Works fine for normal paths:

> INFO - Base "test_dir" name "test_dir"
> INFO - File path "" Parent None
> INFO - Base "test_dir" name "test_dir/dir_unreadable"
> INFO - File path "dir_unreadable" Parent Some("")
> INFO - Base "test_dir" name "test_dir/dir_unreadable/345"
> INFO - File path "dir_unreadable/345" Parent Some("dir_unreadable")

And yelds nothing for paths, starting with "..":

> INFO - Base "../../Projects/vms/" name "../../Projects/vms/"
> INFO - File path "" Parent None
> INFO - Base "../../Projects/vms/" name "../../Projects/vms/kernels"
> INFO - File path "" Parent None
> INFO - Base "../../Projects/vms/" name "../../Projects/vms/kernels/net.img"
> INFO - File path "" Parent None

But should give something like:
> INFO - Base "../../Projects/vms/" name "../../Projects/vms/"
> INFO - File path "" Parent None
> INFO - Base "../../Projects/vms/" name "../../Projects/vms/kernels"
> INFO - File path "kernels" Parent Parent Some("")
> INFO - Base "../../Projects/vms/" name "../../Projects/vms/kernels/net.img"
> INFO - File path "kernels/net.img" Parent Some("kernels")

**Comment by udoprog** [comment]
So yeah. Function currently doesn't work if the relative path being traversed *from* has any `ParentDir` components (<https://github.com/udoprog/relative-path/blob/main/src/lib.rs#L1510>). I'd say the cases you've outline should probably be supported though. Them having a common prefix is probably a case that should be supported though so I'm marking this as a bug.

It would also probably be good to switch to an algorithm which doesn't use `relative_traversal` which allocates two vectors to do the work.

**Comment by Gordon01** [comment]
Thank you for a quick reply and help!

By the way, I'm interested, why you haven't bound the RelativePath to the absolute path? This can make a library more robust and solve the problem with unnamed components?

**Comment by udoprog** [comment]
You'd have to add functions to interact with an actual filesystem which is out of scope for this. `relative-path` only performs logical manipulation as a principle to allow them to be as portable as possible. We can always convert this to a path (using `RelativePath::to_path` et. al.) and apply whatever processing we feel appropriate to the resulting `PathBuf`.

**Comment by Gordon01** [comment]
But what exactly binds us to interact with an actual filesystem? We still can parse the absolute path logically. I'll try to make some examples tomorrow to show the concept.
