### ISSUE TITLE
Documentation and behavior mismatch for RelativePathBuf::push

### ISSUE THREAD

**Issue by stormshield-guillaumed** [udoprog/relative-path#44]
From the `RelativePathBuf::push` documentation :
```md
Extends `self` with `path`.

If `path` is absolute, it replaces the current path.
```
When I run this code :
```rust
let mut path = RelativePathBuf::from("a/b/c");
path.push("/d/e/f");
println!("{}", path);
```
It prints :
```
a/b/c/d/e/f
```
This is the expected result but the documentation says otherwise.

**Comment by mhnap** [comment]
I also caught this. It would be great to remove this from the docs. Thanks!

**Comment by udoprog** [comment]
Removed and released a documentation fix. Thank you!
