### ISSUE TITLE
Case sensitivity is a portability hazard

### ISSUE THREAD

**Issue by coderedart** [udoprog/relative-path#45]
Windows paths seem to be case insensitive. But unix paths are usually case sensitive. It would be better to mention this portability issue in README or docs, as this is a pretty big quirk.

reference: https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

**Comment by udoprog** [comment]
Hah, that's fair. It's not supposed to be en exhaustive list.

If you have a good phrasing in mind, feel free to add it!
