### ISSUE TITLE
Implement `Display` for RelativePath[Buf]

### ISSUE THREAD

**Issue by matklad** [udoprog/relative-path#6]
The reason why `std` does not implement `Display` for `Path` and `PathBuf` is that they can contain invalid unicode, and it's unclear how to display that.

However, relative paths are guranteed to be unicode, so we can just display the underlying `str`?

**Comment by udoprog** [comment]
Thanks @matklad <3

There are some details about API compatibility with `std::path::Path` that you might be interested to look over in #6. I'd appreciate your take on that.
