### ISSUE TITLE
Component::CurDir missing

### ISSUE THREAD

**Issue by ratmice** [udoprog/relative-path#8]
I noticed that Component::CurDir is missing, which I was hoping to use as a marker for splitting off a prefix. Having tried Normal(".")... that doesn't ever match, because it looks as though Components::iter(), skips over these via the function scan_separator here:
https://github.com/udoprog/relative-path/blob/master/src/lib.rs#L110-L113

Is this intended to happen before normalize() is called?

**Comment by udoprog** [comment]
It's intended to completely skip over, but if you have a use-case where you don't find that desirable I'll be happy to incorporate a patch for this.
